import jax.numpy as jnp

RINK_LENGTH = 61.
RINK_WIDTH = 30.
GOAL_X = 55.
GOAL_Y = RINK_WIDTH / 2
GOAL_R = 3.
OPPONENT_X_1 = RINK_LENGTH - 16.
OPPONENT_Y_1 = RINK_WIDTH / 2. + 7
OPPONENT_X_2 = RINK_LENGTH - 16.
OPPONENT_Y_2 = RINK_WIDTH / 2 - 7.
OPPONENT_X_3 = RINK_LENGTH - 32.
OPPONENT_Y_3 = RINK_WIDTH / 2 + 10.
OPPONENT_X_4 = RINK_LENGTH - 32.
OPPONENT_Y_4 = RINK_WIDTH / 2 - 10.
OPPONENT_X_5 = RINK_LENGTH - 40
OPPONENT_Y_5 = RINK_WIDTH / 2
OPPONENT_X = jnp.array([OPPONENT_X_1, OPPONENT_X_2, OPPONENT_X_3, OPPONENT_X_4, OPPONENT_X_5])
OPPONENT_Y = jnp.array([OPPONENT_Y_1, OPPONENT_Y_2, OPPONENT_Y_3, OPPONENT_Y_4, OPPONENT_Y_5])
OPPONENT_R = 2.
NUM_OPS = 5
N = 5
M = 2
T = 8
DT = 0.01
VALS_NT = 101

